SELECT ao.ANIMAL_ID, ao.ANIMAL_TYPE, ao.NAME
FROM ANIMAL_INS ai
INNER JOIN ANIMAL_OUTS ao ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE NOT (ai.SEX_UPON_INTAKE REGEXP "Neutered|Spayed") AND ao.SEX_UPON_OUTCOME REGEXP "Neutered|Spayed"
ORDER BY ao.ANIMAL_ID ASC;