SELECT m.MEMBER_ID, m.MEMBER_NAME, m.GENDER, DATE_FORMAT(m.DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE m
WHERE MONTH(m.DATE_OF_BIRTH) = 3 AND m.GENDER = "W" AND m.TLNO IS NOT NULL
ORDER BY m.MEMBER_ID ASC;