SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m
INNER JOIN REST_REVIEW r ON r.MEMBER_ID = m.MEMBER_ID
WHERE m.MEMBER_ID = (
    SELECT m2.MEMBER_ID
    FROM MEMBER_PROFILE m2
    INNER JOIN REST_REVIEW r2 ON r2.MEMBER_ID = m2.MEMBER_ID
    GROUP BY m2.MEMBER_ID
    ORDER BY COUNT(r2.REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, r.REVIEW_TEXT ASC;